export interface AudioTag {
  id: string;
  label: string;
  category: string;
  description: string;
}

// These are the default lit-text-ui tags
export const defaultTags: AudioTag[] = [
  {id: "sigh", label: "[sigh]", category: "Non-Speech", description: "Inserts a sigh sound."},
  {id: "laughing", label: "[laughing]", category: "Non-Speech", description: "Inserts a laugh."},
  {id: "uhm", label: "[uhm]", category: "Non-Speech", description: "Inserts a hesitation sound."},
  {id: "sarcasm", label: "[sarcasm]", category: "Style", description: "Sarcastic tone on subsequent phrase."},
  {id: "robotic", label: "[robotic]", category: "Style", description: "Makes subsequent speech sound robotic."},
  {id: "shouting", label: "[shouting]", category: "Style", description: "Increases volume."},
  {id: "whispering", label: "[whispering]", category: "Style", description: "Decreases volume."},
  {id: "extremely fast", label: "[extremely fast]", category: "Style", description: "Increases speed."},
  {id: "scared", label: "[scared]", category: "Vocalized", description: "Word is spoken; scared tone."},
  {id: "curious", label: "[curious]", category: "Vocalized", description: "Word is spoken; curious tone."},
  {id: "bored", label: "[bored]", category: "Vocalized", description: "Word is spoken; bored delivery."},
  {id: "short pause", label: "[short pause]", category: "Pacing", description: "~250ms pause."},
  {id: "medium pause", label: "[medium pause]", category: "Pacing", description: "~500ms pause."},
  {id: "long pause", label: "[long pause]", category: "Pacing", description: "~1000ms pause."}
];

export const extendedTags: AudioTag[] = [
  { id: 'admiration', label: '[admiration]', category: 'Vocalized', description: 'Applies admiration delivery.' },
  { id: 'enthusiasm', label: '[enthusiasm]', category: 'Vocalized', description: 'Applies enthusiasm delivery.' },
  { id: 'acceptance', label: '[acceptance]', category: 'Vocalized', description: 'Applies acceptance delivery.' },
  { id: 'accomplishment', label: '[accomplishment]', category: 'Vocalized', description: 'Applies accomplishment delivery.' },
  { id: 'achievement', label: '[achievement]', category: 'Vocalized', description: 'Applies achievement delivery.' },
  { id: 'action', label: '[action]', category: 'Vocalized', description: 'Applies action delivery.' },
  { id: 'admonition', label: '[admonition]', category: 'Vocalized', description: 'Applies admonition delivery.' },
  { id: 'adoration', label: '[adoration]', category: 'Vocalized', description: 'Applies adoration delivery.' },
  { id: 'aesthetic appreciation', label: '[aesthetic appreciation]', category: 'Vocalized', description: 'Applies aesthetic appreciation delivery.' },
  { id: 'affection', label: '[affection]', category: 'Vocalized', description: 'Applies affection delivery.' },
  { id: 'aggression', label: '[aggression]', category: 'Vocalized', description: 'Applies aggression delivery.' },
  { id: 'agitation', label: '[agitation]', category: 'Vocalized', description: 'Applies agitation delivery.' },
  { id: 'alarm', label: '[alarm]', category: 'Vocalized', description: 'Applies alarm delivery.' },
  { id: 'amazement', label: '[amazement]', category: 'Vocalized', description: 'Applies amazement delivery.' },
  { id: 'ambivalence', label: '[ambivalence]', category: 'Vocalized', description: 'Applies ambivalence delivery.' },
  { id: 'amused', label: '[amused]', category: 'Vocalized', description: 'Applies amused delivery.' },
  { id: 'amusement', label: '[amusement]', category: 'Vocalized', description: 'Applies amusement delivery.' },
  { id: 'analysis', label: '[analysis]', category: 'Vocalized', description: 'Applies analysis delivery.' },
  { id: 'anger', label: '[anger]', category: 'Vocalized', description: 'Applies anger delivery.' },
  { id: 'animation', label: '[animation]', category: 'Vocalized', description: 'Applies animation delivery.' },
  { id: 'annoyance', label: '[annoyance]', category: 'Vocalized', description: 'Applies annoyance delivery.' },
  { id: 'anticipation', label: '[anticipation]', category: 'Vocalized', description: 'Applies anticipation delivery.' },
  { id: 'anxiety', label: '[anxiety]', category: 'Vocalized', description: 'Applies anxiety delivery.' },
  { id: 'apology', label: '[apology]', category: 'Vocalized', description: 'Applies apology delivery.' },
  { id: 'appreciation', label: '[appreciation]', category: 'Vocalized', description: 'Applies appreciation delivery.' },
  { id: 'apprehension', label: '[apprehension]', category: 'Vocalized', description: 'Applies apprehension delivery.' },
  { id: 'approval', label: '[approval]', category: 'Vocalized', description: 'Applies approval delivery.' },
  { id: 'arrogance', label: '[arrogance]', category: 'Vocalized', description: 'Applies arrogance delivery.' },
  { id: 'assertion', label: '[assertion]', category: 'Vocalized', description: 'Applies assertion delivery.' },
  { id: 'assertive', label: '[assertive]', category: 'Vocalized', description: 'Applies assertive delivery.' },
  { id: 'assertiveness', label: '[assertiveness]', category: 'Vocalized', description: 'Applies assertiveness delivery.' },
  { id: 'assurance', label: '[assurance]', category: 'Vocalized', description: 'Applies assurance delivery.' },
  { id: 'asterisk', label: '[asterisk]', category: 'Pacing', description: 'Applies asterisk delivery.' },
  { id: 'astonishment', label: '[astonishment]', category: 'Vocalized', description: 'Applies astonishment delivery.' },
  { id: 'aversion', label: '[aversion]', category: 'Vocalized', description: 'Applies aversion delivery.' },
  { id: 'awareness', label: '[awareness]', category: 'Vocalized', description: 'Applies awareness delivery.' },
  { id: 'awe', label: '[awe]', category: 'Vocalized', description: 'Applies awe delivery.' },
  { id: 'awkwardness', label: '[awkwardness]', category: 'Vocalized', description: 'Applies awkwardness delivery.' },
  { id: 'bargaining', label: '[bargaining]', category: 'Vocalized', description: 'Applies bargaining delivery.' },
  { id: 'boredom', label: '[boredom]', category: 'Vocalized', description: 'Applies boredom delivery.' },
  { id: 'caring', label: '[caring]', category: 'Vocalized', description: 'Applies caring delivery.' },
  { id: 'caution', label: '[caution]', category: 'Vocalized', description: 'Applies caution delivery.' },
  { id: 'cautious', label: '[cautious]', category: 'Vocalized', description: 'Applies cautious delivery.' },
  { id: 'certainty', label: '[certainty]', category: 'Vocalized', description: 'Applies certainty delivery.' },
  { id: 'challenging', label: '[challenging]', category: 'Vocalized', description: 'Applies challenging delivery.' },
  { id: 'comfort', label: '[comfort]', category: 'Vocalized', description: 'Applies comfort delivery.' },
  { id: 'compassion', label: '[compassion]', category: 'Vocalized', description: 'Applies compassion delivery.' },
  { id: 'concentration', label: '[concentration]', category: 'Vocalized', description: 'Applies concentration delivery.' },
  { id: 'concern', label: '[concern]', category: 'Vocalized', description: 'Applies concern delivery.' },
  { id: 'confidence', label: '[confidence]', category: 'Vocalized', description: 'Applies confidence delivery.' },
  { id: 'confident', label: '[confident]', category: 'Vocalized', description: 'Applies confident delivery.' },
  { id: 'confident/neutral', label: '[confident/neutral]', category: 'Vocalized', description: 'Applies confident/neutral delivery.' },
  { id: 'confusion', label: '[confusion]', category: 'Vocalized', description: 'Applies confusion delivery.' },
  { id: 'contemplative', label: '[contemplative]', category: 'Vocalized', description: 'Applies contemplative delivery.' },
  { id: 'contempt', label: '[contempt]', category: 'Vocalized', description: 'Applies contempt delivery.' },
  { id: 'contentment', label: '[contentment]', category: 'Vocalized', description: 'Applies contentment delivery.' },
  { id: 'conviction', label: '[conviction]', category: 'Vocalized', description: 'Applies conviction delivery.' },
  { id: 'courage', label: '[courage]', category: 'Vocalized', description: 'Applies courage delivery.' },
  { id: 'craving', label: '[craving]', category: 'Vocalized', description: 'Applies craving delivery.' },
  { id: 'critical', label: '[critical]', category: 'Vocalized', description: 'Applies critical delivery.' },
  { id: 'criticism', label: '[criticism]', category: 'Vocalized', description: 'Applies criticism delivery.' },
  { id: 'curiosity', label: '[curiosity]', category: 'Vocalized', description: 'Applies curiosity delivery.' },
  { id: 'decision', label: '[decision]', category: 'Vocalized', description: 'Applies decision delivery.' },
  { id: 'defiance', label: '[defiance]', category: 'Vocalized', description: 'Applies defiance delivery.' },
  { id: 'demonstration', label: '[demonstration]', category: 'Vocalized', description: 'Applies demonstration delivery.' },
  { id: 'description', label: '[description]', category: 'Vocalized', description: 'Applies description delivery.' },
  { id: 'descriptive', label: '[descriptive]', category: 'Vocalized', description: 'Applies descriptive delivery.' },
  { id: 'desire', label: '[desire]', category: 'Vocalized', description: 'Applies desire delivery.' },
  { id: 'despair', label: '[despair]', category: 'Vocalized', description: 'Applies despair delivery.' },
  { id: 'desperation', label: '[desperation]', category: 'Vocalized', description: 'Applies desperation delivery.' },
  { id: 'despondency', label: '[despondency]', category: 'Vocalized', description: 'Applies despondency delivery.' },
  { id: 'determination', label: '[determination]', category: 'Vocalized', description: 'Applies determination delivery.' },
  { id: 'determined', label: '[determined]', category: 'Vocalized', description: 'Applies determined delivery.' },
  { id: 'devotion', label: '[devotion]', category: 'Vocalized', description: 'Applies devotion delivery.' },
  { id: 'directness', label: '[directness]', category: 'Vocalized', description: 'Applies directness delivery.' },
  { id: 'disagreement', label: '[disagreement]', category: 'Vocalized', description: 'Applies disagreement delivery.' },
  { id: 'disappointment', label: '[disappointment]', category: 'Vocalized', description: 'Applies disappointment delivery.' },
  { id: 'disapproval', label: '[disapproval]', category: 'Vocalized', description: 'Applies disapproval delivery.' },
  { id: 'disbelief', label: '[disbelief]', category: 'Vocalized', description: 'Applies disbelief delivery.' },
  { id: 'discernment', label: '[discernment]', category: 'Vocalized', description: 'Applies discernment delivery.' },
  { id: 'discomfort', label: '[discomfort]', category: 'Vocalized', description: 'Applies discomfort delivery.' },
  { id: 'disdain', label: '[disdain]', category: 'Vocalized', description: 'Applies disdain delivery.' },
  { id: 'disgust', label: '[disgust]', category: 'Vocalized', description: 'Applies disgust delivery.' },
  { id: 'disillusionment', label: '[disillusionment]', category: 'Vocalized', description: 'Applies disillusionment delivery.' },
  { id: 'dislike', label: '[dislike]', category: 'Vocalized', description: 'Applies dislike delivery.' },
  { id: 'dismissal', label: '[dismissal]', category: 'Vocalized', description: 'Applies dismissal delivery.' },
  { id: 'dismissive', label: '[dismissive]', category: 'Vocalized', description: 'Applies dismissive delivery.' },
  { id: 'dismissiveness', label: '[dismissiveness]', category: 'Vocalized', description: 'Applies dismissiveness delivery.' },
  { id: 'distress', label: '[distress]', category: 'Vocalized', description: 'Applies distress delivery.' },
  { id: 'doubt', label: '[doubt]', category: 'Vocalized', description: 'Applies doubt delivery.' },
  { id: 'dread', label: '[dread]', category: 'Vocalized', description: 'Applies dread delivery.' },
  { id: 'eagerness', label: '[eagerness]', category: 'Vocalized', description: 'Applies eagerness delivery.' },
  { id: 'effervescence', label: '[effervescence]', category: 'Vocalized', description: 'Applies effervescence delivery.' },
  { id: 'embarrassment', label: '[embarrassment]', category: 'Vocalized', description: 'Applies embarrassment delivery.' },
  { id: 'embitterment', label: '[embitterment]', category: 'Vocalized', description: 'Applies embitterment delivery.' },
  { id: 'embracement', label: '[embracement]', category: 'Vocalized', description: 'Applies embracement delivery.' },
  { id: 'empathy', label: '[empathy]', category: 'Vocalized', description: 'Applies empathy delivery.' },
  { id: 'emphasis', label: '[emphasis]', category: 'Vocalized', description: 'Applies emphasis delivery.' },
  { id: 'enchantment', label: '[enchantment]', category: 'Vocalized', description: 'Applies enchantment delivery.' },
  { id: 'encouragement', label: '[encouragement]', category: 'Vocalized', description: 'Applies encouragement delivery.' },
  { id: 'encouraging', label: '[encouraging]', category: 'Vocalized', description: 'Applies encouraging delivery.' },
  { id: 'energetic', label: '[energetic]', category: 'Vocalized', description: 'Applies energetic delivery.' },
  { id: 'energy', label: '[energy]', category: 'Style', description: 'Applies energy delivery.' },
  { id: 'enjoyment', label: '[enjoyment]', category: 'Vocalized', description: 'Applies enjoyment delivery.' },
  { id: 'enthusiastic', label: '[enthusiastic]', category: 'Vocalized', description: 'Applies enthusiastic delivery.' },
  { id: 'excitement', label: '[excitement]', category: 'Vocalized', description: 'Applies excitement delivery.' },
  { id: 'exhaustion', label: '[exhaustion]', category: 'Vocalized', description: 'Applies exhaustion delivery.' },
  { id: 'explaining', label: '[explaining]', category: 'Vocalized', description: 'Applies explaining delivery.' },
  { id: 'explanation', label: '[explanation]', category: 'Vocalized', description: 'Applies explanation delivery.' },
  { id: 'explanatory', label: '[explanatory]', category: 'Vocalized', description: 'Applies explanatory delivery.' },
  { id: 'fascination', label: '[fascination]', category: 'Vocalized', description: 'Applies fascination delivery.' },
  { id: 'fear', label: '[fear]', category: 'Vocalized', description: 'Applies fear delivery.' },
  { id: 'focus', label: '[focus]', category: 'Vocalized', description: 'Applies focus delivery.' },
  { id: 'fondness', label: '[fondness]', category: 'Vocalized', description: 'Applies fondness delivery.' },
  { id: 'friendliness', label: '[friendliness]', category: 'Vocalized', description: 'Applies friendliness delivery.' },
  { id: 'friendly', label: '[friendly]', category: 'Vocalized', description: 'Applies friendly delivery.' },
  { id: 'frustration', label: '[frustration]', category: 'Vocalized', description: 'Applies frustration delivery.' },
  { id: 'gratification', label: '[gratification]', category: 'Vocalized', description: 'Applies gratification delivery.' },
  { id: 'gratitude', label: '[gratitude]', category: 'Vocalized', description: 'Applies gratitude delivery.' },
  { id: 'grief', label: '[grief]', category: 'Vocalized', description: 'Applies grief delivery.' },
  { id: 'guilt', label: '[guilt]', category: 'Vocalized', description: 'Applies guilt delivery.' },
  { id: 'happiness', label: '[happiness]', category: 'Vocalized', description: 'Applies happiness delivery.' },
  { id: 'happy', label: '[happy]', category: 'Vocalized', description: 'Applies happy delivery.' },
  { id: 'high energy/active', label: '[high energy/active]', category: 'Style', description: 'Applies high energy/active delivery.' },
  { id: 'hope', label: '[hope]', category: 'Vocalized', description: 'Applies hope delivery.' },
  { id: 'horror', label: '[horror]', category: 'Vocalized', description: 'Applies horror delivery.' },
  { id: 'humor', label: '[humor]', category: 'Vocalized', description: 'Applies humor delivery.' },
  { id: 'hurt', label: '[hurt]', category: 'Vocalized', description: 'Applies hurt delivery.' },
  { id: 'incredulity', label: '[incredulity]', category: 'Vocalized', description: 'Applies incredulity delivery.' },
  { id: 'indifference', label: '[indifference]', category: 'Vocalized', description: 'Applies indifference delivery.' },
  { id: 'indignation', label: '[indignation]', category: 'Vocalized', description: 'Applies indignation delivery.' },
  { id: 'information', label: '[information]', category: 'Vocalized', description: 'Applies information delivery.' },
  { id: 'information disclosure', label: '[information disclosure]', category: 'Vocalized', description: 'Applies information disclosure delivery.' },
  { id: 'informational', label: '[informational]', category: 'Vocalized', description: 'Applies informational delivery.' },
  { id: 'informative', label: '[informative]', category: 'Vocalized', description: 'Applies informative delivery.' },
  { id: 'informativeness', label: '[informativeness]', category: 'Vocalized', description: 'Applies informativeness delivery.' },
  { id: 'instruction', label: '[instruction]', category: 'Vocalized', description: 'Applies instruction delivery.' },
  { id: 'interest', label: '[interest]', category: 'Vocalized', description: 'Applies interest delivery.' },
  { id: 'intrigue', label: '[intrigue]', category: 'Vocalized', description: 'Applies intrigue delivery.' },
  { id: 'invitation', label: '[invitation]', category: 'Vocalized', description: 'Applies invitation delivery.' },
  { id: 'joy', label: '[joy]', category: 'Vocalized', description: 'Applies joy delivery.' },
  { id: 'logical reasoning', label: '[logical reasoning]', category: 'Vocalized', description: 'Applies logical reasoning delivery.' },
  { id: 'love', label: '[love]', category: 'Vocalized', description: 'Applies love delivery.' },
  { id: 'low energy/passive', label: '[low energy/passive]', category: 'Style', description: 'Applies low energy/passive delivery.' },
  { id: 'melancholy', label: '[melancholy]', category: 'Vocalized', description: 'Applies melancholy delivery.' },
  { id: 'mixed', label: '[mixed]', category: 'Vocalized', description: 'Applies mixed delivery.' },
  { id: 'musement', label: '[musement]', category: 'Vocalized', description: 'Applies musement delivery.' },
  { id: 'negative', label: '[negative]', category: 'Vocalized', description: 'Applies negative delivery.' },
  { id: 'negative surprise', label: '[negative surprise]', category: 'Vocalized', description: 'Applies negative surprise delivery.' },
  { id: 'nervousness', label: '[nervousness]', category: 'Vocalized', description: 'Applies nervousness delivery.' },
  { id: 'neutral', label: '[neutral]', category: 'Vocalized', description: 'Applies neutral delivery.' },
  { id: 'none', label: '[none]', category: 'Vocalized', description: 'Applies none delivery.' },
  { id: 'nostalgia', label: '[nostalgia]', category: 'Vocalized', description: 'Applies nostalgia delivery.' },
  { id: 'observation', label: '[observation]', category: 'Vocalized', description: 'Applies observation delivery.' },
  { id: 'offense', label: '[offense]', category: 'Vocalized', description: 'Applies offense delivery.' },
  { id: 'optimism', label: '[optimism]', category: 'Vocalized', description: 'Applies optimism delivery.' },
  { id: 'pain', label: '[pain]', category: 'Vocalized', description: 'Applies pain delivery.' },
  { id: 'panic', label: '[panic]', category: 'Vocalized', description: 'Applies panic delivery.' },
  { id: 'passion', label: '[passion]', category: 'Vocalized', description: 'Applies passion delivery.' },
  { id: 'pensive', label: '[pensive]', category: 'Vocalized', description: 'Applies pensive delivery.' },
  { id: 'pessimism', label: '[pessimism]', category: 'Vocalized', description: 'Applies pessimism delivery.' },
  { id: 'pity', label: '[pity]', category: 'Vocalized', description: 'Applies pity delivery.' },
  { id: 'planning', label: '[planning]', category: 'Vocalized', description: 'Applies planning delivery.' },
  { id: 'playful', label: '[playful]', category: 'Vocalized', description: 'Applies playful delivery.' },
  { id: 'pleading', label: '[pleading]', category: 'Vocalized', description: 'Applies pleading delivery.' },
  { id: 'pleased', label: '[pleased]', category: 'Vocalized', description: 'Applies pleased delivery.' },
  { id: 'positive', label: '[positive]', category: 'Vocalized', description: 'Applies positive delivery.' },
  { id: 'positive surprise', label: '[positive surprise]', category: 'Vocalized', description: 'Applies positive surprise delivery.' },
  { id: 'praise', label: '[praise]', category: 'Vocalized', description: 'Applies praise delivery.' },
  { id: 'pride', label: '[pride]', category: 'Vocalized', description: 'Applies pride delivery.' },
  { id: 'realization', label: '[realization]', category: 'Vocalized', description: 'Applies realization delivery.' },
  { id: 'recognition', label: '[recognition]', category: 'Vocalized', description: 'Applies recognition delivery.' },
  { id: 'reflection', label: '[reflection]', category: 'Vocalized', description: 'Applies reflection delivery.' },
  { id: 'regret', label: '[regret]', category: 'Vocalized', description: 'Applies regret delivery.' },
  { id: 'relaxation', label: '[relaxation]', category: 'Vocalized', description: 'Applies relaxation delivery.' },
  { id: 'relief', label: '[relief]', category: 'Vocalized', description: 'Applies relief delivery.' },
  { id: 'reminiscence', label: '[reminiscence]', category: 'Vocalized', description: 'Applies reminiscence delivery.' },
  { id: 'resignation', label: '[resignation]', category: 'Vocalized', description: 'Applies resignation delivery.' },
  { id: 'sadness', label: '[sadness]', category: 'Vocalized', description: 'Applies sadness delivery.' },
  { id: 'sarcasm', label: '[sarcasm]', category: 'Vocalized', description: 'Applies sarcasm delivery.' },
  { id: 'satisfaction', label: '[satisfaction]', category: 'Vocalized', description: 'Applies satisfaction delivery.' },
  { id: 'self-deprecation', label: '[self-deprecation]', category: 'Vocalized', description: 'Applies self-deprecation delivery.' },
  { id: 'self-satisfaction', label: '[self-satisfaction]', category: 'Vocalized', description: 'Applies self-satisfaction delivery.' },
  { id: 'sentimentality', label: '[sentimentality]', category: 'Vocalized', description: 'Applies sentimentality delivery.' },
  { id: 'serenity', label: '[serenity]', category: 'Vocalized', description: 'Applies serenity delivery.' },
  { id: 'seriousness', label: '[seriousness]', category: 'Vocalized', description: 'Applies seriousness delivery.' },
  { id: 'shame', label: '[shame]', category: 'Vocalized', description: 'Applies shame delivery.' },
  { id: 'shock', label: '[shock]', category: 'Vocalized', description: 'Applies shock delivery.' },
  { id: 'skepticism', label: '[skepticism]', category: 'Vocalized', description: 'Applies skepticism delivery.' },
  { id: 'slight relief', label: '[slight relief]', category: 'Vocalized', description: 'Applies slight relief delivery.' },
  { id: 'smitten', label: '[smitten]', category: 'Vocalized', description: 'Applies smitten delivery.' },
  { id: 'solemnity', label: '[solemnity]', category: 'Vocalized', description: 'Applies solemnity delivery.' },
  { id: 'speculation', label: '[speculation]', category: 'Vocalized', description: 'Applies speculation delivery.' },
  { id: 'spk1', label: '[spk1]', category: 'Vocalized', description: 'Applies spk1 delivery.' },
  { id: 'strategizing', label: '[strategizing]', category: 'Vocalized', description: 'Applies strategizing delivery.' },
  { id: 'stress', label: '[stress]', category: 'Vocalized', description: 'Applies stress delivery.' },
  { id: 'struggle', label: '[struggle]', category: 'Vocalized', description: 'Applies struggle delivery.' },
  { id: 'success', label: '[success]', category: 'Vocalized', description: 'Applies success delivery.' },
  { id: 'suffering', label: '[suffering]', category: 'Vocalized', description: 'Applies suffering delivery.' },
  { id: 'suggestion', label: '[suggestion]', category: 'Vocalized', description: 'Applies suggestion delivery.' },
  { id: 'summary', label: '[summary]', category: 'Vocalized', description: 'Applies summary delivery.' },
  { id: 'surprise', label: '[surprise]', category: 'Vocalized', description: 'Applies surprise delivery.' },
  { id: 'suspicion', label: '[suspicion]', category: 'Vocalized', description: 'Applies suspicion delivery.' },
  { id: 'sympathy', label: '[sympathy]', category: 'Vocalized', description: 'Applies sympathy delivery.' },
  { id: 'tension', label: '[tension]', category: 'Vocalized', description: 'Applies tension delivery.' },
  { id: 'terror', label: '[terror]', category: 'Vocalized', description: 'Applies terror delivery.' },
  { id: 'thanks', label: '[thanks]', category: 'Vocalized', description: 'Applies thanks delivery.' },
  { id: 'thinking', label: '[thinking]', category: 'Vocalized', description: 'Applies thinking delivery.' },
  { id: 'thoughtful', label: '[thoughtful]', category: 'Vocalized', description: 'Applies thoughtful delivery.' },
  { id: 'thoughtfulness', label: '[thoughtfulness]', category: 'Vocalized', description: 'Applies thoughtfulness delivery.' },
  { id: 'thrill', label: '[thrill]', category: 'Vocalized', description: 'Applies thrill delivery.' },
  { id: 'tiredness', label: '[tiredness]', category: 'Vocalized', description: 'Applies tiredness delivery.' },
  { id: 'triumph', label: '[triumph]', category: 'Vocalized', description: 'Applies triumph delivery.' },
  { id: 'uncertainty', label: '[uncertainty]', category: 'Vocalized', description: 'Applies uncertainty delivery.' },
  { id: 'unclear', label: '[unclear]', category: 'Vocalized', description: 'Applies unclear delivery.' },
  { id: 'understanding', label: '[understanding]', category: 'Vocalized', description: 'Applies understanding delivery.' },
  { id: 'unease', label: '[unease]', category: 'Vocalized', description: 'Applies unease delivery.' },
  { id: 'urgency', label: '[urgency]', category: 'Vocalized', description: 'Applies urgency delivery.' },
  { id: 'victory', label: '[victory]', category: 'Vocalized', description: 'Applies victory delivery.' },
  { id: 'warning', label: '[warning]', category: 'Vocalized', description: 'Applies warning delivery.' },
  { id: 'weariness', label: '[weariness]', category: 'Vocalized', description: 'Applies weariness delivery.' },
  { id: 'wisdom', label: '[wisdom]', category: 'Vocalized', description: 'Applies wisdom delivery.' },
  { id: 'wistful', label: '[wistful]', category: 'Vocalized', description: 'Applies wistful delivery.' },
  { id: 'worry', label: '[worry]', category: 'Vocalized', description: 'Applies worry delivery.' },
  { id: 'yearning', label: '[yearning]', category: 'Vocalized', description: 'Applies yearning delivery.' }
];

export const allTags = [...defaultTags, ...extendedTags.filter(t => !defaultTags.find(d => d.id === t.id))];
